## Percentage of permanent residence issued to Chinese and Indian nationals in 2015, comparing with the rest of Asia

Data source: [Yearbook of Immigration Statistics 2015, Homeland Security, United States](https://www.dhs.gov/immigration-statistics/yearbook/2015)

In [9]:
from pyecharts import online
online()

import pyexcel as p

sheet=p.get_sheet(file_name="fy2015_table3d.xls")
sheet.top()

pyexcel sheet:
+--------------------------------------------------------------------------------------------------------------+------+------+------+------+------+------+------+------+------+------+
| Table 3.                                                                                                     |      |      |      |      |      |      |      |      |      |      |
+--------------------------------------------------------------------------------------------------------------+------+------+------+------+------+------+------+------+------+------+
| PERSONS OBTAINING LAWFUL PERMANENT RESIDENT STATUS BY REGION AND COUNTRY OF BIRTH: FISCAL YEARS 2006 TO 2015 |      |      |      |      |      |      |      |      |      |      |
+--------------------------------------------------------------------------------------------------------------+------+------+------+------+------+------+------+------+------+------+
|                                                                                                              |      |      |      |      |      |      |      |      |      |      |
+--------------------------------------------------------------------------------------------------------------+------+------+------+------+------+------+------+------+------+------+
| Region and country of birth                                                                                  | 2006 | 2007 | 2008 | 2009 | 2010 | 2011 | 2012 | 2013 | 2014 | 2015 |
+--------------------------------------------------------------------------------------------------------------+------+------+------+------+------+------+------+------+------+------+
| REGION                                                                                                       |      |      |      |      |      |      |      |      |      |      |
+--------------------------------------------------------------------------------------------------------------+------+------+------+------+------+------+------+------+------+------+

Let skip the first three rows because they contain meta data only.

In [10]:
sheet=p.get_sheet(file_name="fy2015_table3d.xls", start_row=3)
sheet.top()

pyexcel sheet:
+-----------------------------+---------+---------+---------+---------+---------+---------+---------+--------+---------+---------+
| Region and country of birth | 2006    | 2007    | 2008    | 2009    | 2010    | 2011    | 2012    | 2013   | 2014    | 2015    |
+-----------------------------+---------+---------+---------+---------+---------+---------+---------+--------+---------+---------+
| REGION                      |         |         |         |         |         |         |         |        |         |         |
+-----------------------------+---------+---------+---------+---------+---------+---------+---------+--------+---------+---------+
| Total                       | 1266129 | 1052415 | 1107126 | 1130818 | 1042625 | 1062040 | 1031631 | 990553 | 1016518 | 1051031 |
+-----------------------------+---------+---------+---------+---------+---------+---------+---------+--------+---------+---------+
| Africa                      | 117421  | 94710   | 105915  | 127046  | 101355  | 100374  | 107241  | 98304  | 98413   | 101415  |
+-----------------------------+---------+---------+---------+---------+---------+---------+---------+--------+---------+---------+
| Asia                        | 440335  | 397834  | 399027  | 413312  | 422063  | 451593  | 429599  | 400548 | 430508  | 419297  |
+-----------------------------+---------+---------+---------+---------+---------+---------+---------+--------+---------+---------+

In [11]:
sheet.name_rows_by_column(0)
sheet.row.select(['Region and country of birth','Asia', 'India', 'China, People\'s Republic'])
sheet

Table 3 D:
+-----------------------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+
| Region and country of birth | 2006   | 2007   | 2008   | 2009   | 2010   | 2011   | 2012   | 2013   | 2014   | 2015   |
+-----------------------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+
| Asia                        | 440335 | 397834 | 399027 | 413312 | 422063 | 451593 | 429599 | 400548 | 430508 | 419297 |
+-----------------------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+
| China, People's Republic    | 87307  | 76655  | 80271  | 64238  | 70863  | 87016  | 81784  | 71798  | 76089  | 74558  |
+-----------------------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+
| India                       | 61369  | 65353  | 63352  | 57304  | 69162  | 69013  | 66434  | 68458  | 77908  | 64116  |
+-----------------------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+

In [12]:
sheet

Table 3 D:
+-----------------------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+
| Region and country of birth | 2006   | 2007   | 2008   | 2009   | 2010   | 2011   | 2012   | 2013   | 2014   | 2015   |
+-----------------------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+
| Asia                        | 440335 | 397834 | 399027 | 413312 | 422063 | 451593 | 429599 | 400548 | 430508 | 419297 |
+-----------------------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+
| China, People's Republic    | 87307  | 76655  | 80271  | 64238  | 70863  | 87016  | 81784  | 71798  | 76089  | 74558  |
+-----------------------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+
| India                       | 61369  | 65353  | 63352  | 57304  | 69162  | 69013  | 66434  | 68458  | 77908  | 64116  |
+-----------------------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+

In [13]:
sheet.plot.line()

In [14]:
sheet.transpose()
sheet

Table 3 D:
+------+--------+--------------------------+-------+
|      |  Asia  | China, People's Republic | India |
+======+========+==========================+=======+
| 2006 | 440335 | 87307                    | 61369 |
+------+--------+--------------------------+-------+
| 2007 | 397834 | 76655                    | 65353 |
+------+--------+--------------------------+-------+
| 2008 | 399027 | 80271                    | 63352 |
+------+--------+--------------------------+-------+
| 2009 | 413312 | 64238                    | 57304 |
+------+--------+--------------------------+-------+
| 2010 | 422063 | 70863                    | 69162 |
+------+--------+--------------------------+-------+
| 2011 | 451593 | 87016                    | 69013 |
+------+--------+--------------------------+-------+
| 2012 | 429599 | 81784                    | 66434 |
+------+--------+--------------------------+-------+
| 2013 | 400548 | 71798                    | 68458 |
+------+--------+--------------------------+-------+
| 2014 | 430508 | 76089                    | 77908 |
+------+--------+--------------------------+-------+
| 2015 | 419297 | 74558                    | 64116 |
+------+--------+--------------------------+-------+

In [15]:
pie_dict = {}
pie_dict['China'] = float(sheet['2015', 'China, People\'s Republic'])/sheet['2015', 'Asia']
pie_dict['India'] = float(sheet['2015', 'India'])/sheet['2015', 'Asia']
pie_dict['The Rest of Asia'] = 1 - pie_dict['China'] - pie_dict['India']
pie_sheet = p.get_sheet(adict=pie_dict)
pie_sheet

pyexcel_sheet1:
+---------------+----------------+------------------+
| China         | India          | The Rest of Asia |
+---------------+----------------+------------------+
| 0.17781667887 | 0.152913090244 | 0.669270230886   |
+---------------+----------------+------------------+

In [16]:
pie_sheet.title = 'Percentage of permanent residence issued to Chinese and Indian nationals in 2015, comparing with the rest of Asia'

pie_sheet.plot.pie()